[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cvxpy>=1.7.5",
    "numpy>=2.3.5",
    "python-sat>=1.8.dev24",
    "scipy>=1.16.3",
    "z3-solver>=4.15.4.0",
]
